"""Remove id from Password and UserToken

Revision ID: 23b2a3dec85b
Revises: 4b52c2a28e9a
Create Date: 2022-03-10 12:33:50.017006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23b2a3dec85b"
down_revision = "4b52c2a28e9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_passwords_id", "passwords", type_="unique")
    op.drop_column("passwords", "id")
    op.drop_constraint("uq_user_tokens_id", "user_tokens", type_="unique")
    op.drop_column("user_tokens", "id")
    op.create_unique_constraint(op.f("uq_users_id"), "users", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_id"), "users", type_="unique")
    op.add_column(
        "user_tokens",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("uq_user_tokens_id", "user_tokens", ["id"])
    op.add_column(
        "passwords",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("uq_passwords_id", "passwords", ["id"])
    # ### end Alembic commands ###
